const apiTranslations={
  es:{back:'Volver al portafolio',eyebrow:'Demo 03 · Diseño de APIs',intro:'Un playground local para explorar contratos REST, validación, autenticación, estados HTTP y respuestas consistentes sin enviar información a un servidor.',disclaimer:'Simulación ejecutada completamente en el navegador con datos ficticios.',checkins:'Check-ins',run:'Enviar petición',authenticated:'Autenticada',body:'Cuerpo de petición',response:'Respuesta',validation:'Validación en el límite',validationBody:'El contrato rechaza datos inválidos antes de ejecutar la lógica de negocio.',errors:'Errores consistentes',errorsBody:'Cada fallo devuelve código, mensaje seguro y detalles accionables.',layers:'Responsabilidades separadas',layersBody:'Transporte, caso de uso y acceso a datos evolucionan de forma independiente.',sent:'Petición simulada correctamente.',invalidJson:'El cuerpo no contiene JSON válido.'},
  en:{back:'Back to portfolio',eyebrow:'Demo 03 · API design',intro:'A local playground for exploring REST contracts, validation, authentication, HTTP status codes, and consistent responses without sending data to a server.',disclaimer:'Simulation runs entirely in your browser with fictional data.',checkins:'Check-ins',run:'Send request',authenticated:'Authenticated',body:'Request body',response:'Response',validation:'Boundary validation',validationBody:'The contract rejects invalid data before business logic runs.',errors:'Consistent errors',errorsBody:'Every failure returns a code, a safe message, and actionable details.',layers:'Separated responsibilities',layersBody:'Transport, use case, and data access can evolve independently.',sent:'Simulated request completed.',invalidJson:'The request body is not valid JSON.'}
};
let language='es';
const records=[{id:'CHK-1042',guest:{name:'Maya Chen',email:'maya@example.com'},room:'804',arrival:'2026-10-12',status:'pending',documentsVerified:false},{id:'CHK-1041',guest:{name:'Noah Williams',email:'noah@example.com'},room:'312',arrival:'2026-10-12',status:'ready',documentsVerified:true}];
const routes={
  list:{method:'GET',url:'/api/v1/check-ins',body:'',run:()=>({status:200,data:{items:records,page:1,total:records.length}})},
  get:{method:'GET',url:'/api/v1/check-ins/CHK-1042',body:'',run:()=>({status:200,data:records[0]})},
  create:{method:'POST',url:'/api/v1/check-ins',body:JSON.stringify({guest:{name:'Alex Morgan',email:'alex@example.com'},room:'908',arrival:'2026-10-13'},null,2),run:body=>{if(!body?.guest?.name||!body?.guest?.email||!body?.room)return{status:422,data:{error:'VALIDATION_ERROR',message:'guest.name, guest.email and room are required',details:['Missing required field']}};return{status:201,data:{id:'CHK-1043',...body,status:'pending',documentsVerified:false}}}},
  update:{method:'PATCH',url:'/api/v1/check-ins/CHK-1042',body:JSON.stringify({status:'ready',documentsVerified:true},null,2),run:body=>{if(body.status&&!['pending','ready','completed'].includes(body.status))return{status:422,data:{error:'VALIDATION_ERROR',message:'status must be pending, ready or completed'}};return{status:200,data:{...records[0],...body}}}},
  finish:{method:'POST',url:'/api/v1/check-ins/CHK-1042/finish',body:JSON.stringify({acceptedTerms:true},null,2),run:body=>!body.acceptedTerms?{status:409,data:{error:'TERMS_REQUIRED',message:'Terms must be accepted before completing check-in'}}:{status:200,data:{...records[0],status:'completed',completedAt:new Date().toISOString()}}}
};
let activeRoute='list';const t=key=>apiTranslations[language][key]||key;
function statusText(code){return{200:'OK',201:'CREATED',401:'UNAUTHORIZED',409:'CONFLICT',422:'UNPROCESSABLE ENTITY',500:'INTERNAL SERVER ERROR'}[code]||''}
function selectRoute(name){activeRoute=name;const route=routes[name];document.querySelectorAll('.endpoint').forEach(button=>button.classList.toggle('active',button.dataset.route===name));const method=document.querySelector('#method');method.textContent=route.method;method.className=`method-display ${route.method.toLowerCase()}`;document.querySelector('#url').value=route.url;document.querySelector('#request-body').value=route.body;simulate(false)}
function simulate(showToast=true){const route=routes[activeRoute];let result;const auth=document.querySelector('#auth-toggle').checked;const started=performance.now();if(!auth)result={status:401,data:{error:'UNAUTHORIZED',message:'A valid bearer token is required'}};else{try{const raw=document.querySelector('#request-body').value.trim();const body=raw?JSON.parse(raw):undefined;result=route.run(body)}catch{result={status:422,data:{error:'INVALID_JSON',message:t('invalidJson')}}}}const elapsed=Math.max(18,Math.round(performance.now()-started)+Math.floor(Math.random()*70));const status=document.querySelector('#response-status');status.textContent=`${result.status} ${statusText(result.status)} · ${elapsed} ms`;status.classList.toggle('error',result.status>=400);document.querySelector('#response-body').textContent=JSON.stringify(result.data,null,2);if(showToast)toast(t('sent'))}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2200)}
document.querySelectorAll('.endpoint').forEach(button=>button.addEventListener('click',()=>selectRoute(button.dataset.route)));document.querySelector('#send-request').addEventListener('click',()=>simulate(true));document.querySelector('#auth-toggle').addEventListener('change',()=>simulate(false));
window.setupDemoShell({translations:apiTranslations,onLanguageChange:newLanguage=>{language=newLanguage;simulate(false)}});selectRoute('list');
