const chatTranslations = {
  es:{back:'Volver al portafolio',eyebrow:'Demo 02 · Mensajería',intro:'Una bandeja diseñada para conversaciones operativas. Envía mensajes, corta la conexión y comprueba cómo funcionan los estados y reintentos.',disclaimer:'Producto, personas y mensajes completamente ficticios.',inbox:'Conversaciones',search:'Buscar huésped',online:'En línea',offline:'Sin conexión',messagePlaceholder:'Escribe un mensaje',send:'Enviar',hint:'Prueba desconectar la red y enviar un mensaje.',room:'Habitación',sent:'Enviado',delivered:'Entregado',sending:'Enviando…',failed:'No enviado',retry:'Reintentar',restored:'Conexión restablecida.',lost:'Conexión interrumpida. Los mensajes quedarán pendientes.',empty:'No se encontraron conversaciones.',now:'ahora'},
  en:{back:'Back to portfolio',eyebrow:'Demo 02 · Messaging',intro:'An inbox designed for operational conversations. Send messages, drop the connection, and see delivery states and retries in action.',disclaimer:'Entirely fictional product, people, and messages.',inbox:'Conversations',search:'Search guest',online:'Online',offline:'Offline',messagePlaceholder:'Write a message',send:'Send',hint:'Try going offline and sending a message.',room:'Room',sent:'Sent',delivered:'Delivered',sending:'Sending…',failed:'Not sent',retry:'Retry',restored:'Connection restored.',lost:'Connection interrupted. Messages will remain pending.',empty:'No conversations found.',now:'now'}
};
let language='es';let online=true;let activeId=1;
const conversations=[
  {id:1,name:'Maya Chen',initials:'MC',room:'804',unread:2,preview:{es:'¿La terraza está abierta hoy?',en:'Is the rooftop open tonight?'},messages:[{mine:false,text:{es:'¡Hola! ¿La terraza está abierta hoy?',en:'Hi! Is the rooftop open tonight?'},time:'19:34'},{mine:true,text:{es:'Sí, está abierta hasta las 23:00.',en:'Yes, it is open until 11 PM.'},time:'19:36',state:'delivered'},{mine:false,text:{es:'Perfecto, muchas gracias.',en:'Perfect, thank you so much.'},time:'19:37'}]},
  {id:2,name:'Noah Williams',initials:'NW',room:'312',unread:0,preview:{es:'El aire aún no está enfriando.',en:'The AC is still not cooling.'},messages:[{mine:false,text:{es:'El aire aún no está enfriando.',en:'The AC is still not cooling.'},time:'18:10'},{mine:true,text:{es:'Mantenimiento llegará en diez minutos.',en:'Maintenance will arrive in ten minutes.'},time:'18:12',state:'delivered'}]},
  {id:3,name:'Sofía Almeida',initials:'SA',room:'521',unread:1,preview:{es:'¿Puedo reservar una mesa para cuatro?',en:'Can I book a table for four?'},messages:[{mine:false,text:{es:'¿Puedo reservar una mesa para cuatro?',en:'Can I book a table for four?'},time:'17:42'}]},
  {id:4,name:'Liam Johnson',initials:'LJ',room:'1102',unread:0,preview:{es:'Gracias por confirmar la salida.',en:'Thanks for confirming check-out.'},messages:[{mine:true,text:{es:'Su salida tardía fue confirmada.',en:'Your late check-out was confirmed.'},time:'16:22',state:'delivered'},{mine:false,text:{es:'Gracias por confirmar la salida.',en:'Thanks for confirming check-out.'},time:'16:24'}]}
];
const t=key=>chatTranslations[language][key]||key;const esc=value=>String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2400)}
function renderConversations(){const q=document.querySelector('#conversation-search').value.toLowerCase();const data=conversations.filter(c=>`${c.name} ${c.room}`.toLowerCase().includes(q));document.querySelector('#conversation-list').innerHTML=data.length?data.map(c=>`<button class="conversation ${c.id===activeId?'active':''}" data-id="${c.id}"><span class="avatar">${c.initials}</span><span><strong>${esc(c.name)}</strong><small>${esc(c.preview[language])}</small></span><span><time>19:${30+c.id}</time>${c.unread?`<b class="unread">${c.unread}</b>`:''}</span></button>`).join(''):`<div class="empty">${t('empty')}</div>`;document.querySelectorAll('.conversation').forEach(button=>button.addEventListener('click',()=>{activeId=Number(button.dataset.id);conversations.find(c=>c.id===activeId).unread=0;renderAll()}))}
function renderMessages(){const conversation=conversations.find(c=>c.id===activeId);document.querySelector('#active-avatar').textContent=conversation.initials;document.querySelector('#active-name').textContent=conversation.name;document.querySelector('#active-room').textContent=`${t('room')} ${conversation.room}`;document.querySelector('#messages').innerHTML=conversation.messages.map((m,index)=>`<div class="message ${m.mine?'mine':''} ${m.state==='failed'?'failed':''}">${esc(typeof m.text==='string'?m.text:m.text[language])}<small>${m.time} · ${m.mine?t(m.state||'sent'):''}${m.state==='failed'?` <button class="retry" data-index="${index}">${t('retry')}</button>`:''}</small></div>`).join('');document.querySelectorAll('.retry').forEach(button=>button.addEventListener('click',()=>retryMessage(Number(button.dataset.index))));const area=document.querySelector('#messages');area.scrollTop=area.scrollHeight}
function renderConnection(){const el=document.querySelector('#connection-state');el.textContent=t(online?'online':'offline');el.classList.toggle('offline',!online)}
function renderAll(){renderConversations();renderMessages();renderConnection()}
function retryMessage(index){if(!online){toast(t('lost'));return}const message=conversations.find(c=>c.id===activeId).messages[index];message.state='sending';renderMessages();setTimeout(()=>{message.state='delivered';renderMessages()},700)}
document.querySelector('#conversation-search').addEventListener('input',renderConversations);
document.querySelector('#connection-toggle').addEventListener('click',()=>{online=!online;renderConnection();toast(t(online?'restored':'lost'))});
document.querySelector('#message-form').addEventListener('submit',event=>{event.preventDefault();const input=document.querySelector('#message-input');const value=input.value.trim();if(!value)return;const conversation=conversations.find(c=>c.id===activeId);const message={mine:true,text:value,time:new Intl.DateTimeFormat('en',{hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date()),state:online?'sending':'failed'};conversation.messages.push(message);conversation.preview={es:value,en:value};input.value='';renderAll();if(online)setTimeout(()=>{message.state='sent';renderMessages();setTimeout(()=>{message.state='delivered';renderMessages()},650)},450)});
window.setupDemoShell({translations:chatTranslations,onLanguageChange:newLanguage=>{language=newLanguage;renderAll()}});
